:: Restore previous env vars if any

@set "ECCODES_DEFINITION_PATH="
@set "ECCODES_SAMPLES_PATH="

@if defined _CONDA_SET_ECCODES_DEFINITION_PATH (
    set "ECCODES_DEFINITION_PATH=%_CONDA_SET_ECCODES_DEFINITION_PATH%"
    set "_CONDA_SET_ECCODES_DEFINITION_PATH="
)

@if defined _CONDA_SET_ECCODES_SAMPLES_PATH (
    set "ECCODES_SAMPLES_PATH=%_CONDA_SET_ECCODES_SAMPLES_PATH%"
    set "_CONDA_SET_ECCODES_SAMPLES_PATH="
)
