{% set version = "2.12.3" %}

package:
  name: eccodes
  version: {{ version }}

source:
  url: https://confluence.ecmwf.int/download/attachments/131371724/eccodes-{{ version }}-Source.tar.gz
  sha256: 6dafe2fe3a9994ab2359f8bf8f6bad04dc4f936918999cf01e026323882b6b77

build:
  number: 0
  skip: true  # [win and vc<14]
  detect_binary_files_with_prefix: true
  features:
    - vc14  # [win and py>=35]

requirements:
  build:
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cmake
    - m2-bash  # [win]
    - m2-findutils  # [win]
    - m2-coreutils  # [win]
    - m2-grep  # [win]
    - m2-sed  # [win]
    - m2-gawk  # [win]
    - m2-diffutils  # [win]
    - perl  # [not win]
    - m2-perl  # [win]
    - jasper=1.900.1  # [not win]
    - libpng  # [not win]
    - libnetcdf
    - libaec  # [not win]
    - hdf5
  run:
    - jasper=1.900.1  # [not win]
    - libpng  # [not win]
    - libnetcdf
    - libaec  # [not win]
    - hdf5

test:
  commands:
    - codes_info
    - ls $(codes_info -s)  # [not win]
    - ls $(codes_info -d)  # [not win]
    - for /F "tokens=* USEBACKQ" %%F IN (`codes_info -s`) DO (ls %%F)  # [win]
    - for /F "tokens=* USEBACKQ" %%F IN (`codes_info -d`) DO (ls %%F)  # [win]

about:
  home: https://software.ecmwf.int/wiki/display/ECC/ecCodes+Home
  license: Apache 2.0
  license_family: Apache
  summary: ECMWF ecCodes Copyright 2005-2018 ECMWF.

extra:
  recipe-maintainers:
    - kmuehlbauer
    - kynan
    - ocefpaf
    - pelson
    - StephanSiemen
    - dtip
