{% set version = "2.41.0" %}

package:
  name: eccodes
  version: {{ version }}

source:
  url: https://confluence.ecmwf.int/download/attachments/45757960/eccodes-{{ version }}-Source.tar.gz
  sha256: a1467842e11ed7f62a2f5cc1982e04eec62398f4962e6ba03ace7646f32cf270
  #patches:
  #  - fix_md5_test.patch

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - jasper    # [not ppc64le]
    - openjpeg  # [ppc64le]
    - zlib
    - libpng
    - libnetcdf
    - libaec
    - hdf5

test:
  requires:
    - perl  # [not win]
    - m2-bash  # [win]
    - m2-findutils  # [win]
    - m2-coreutils  # [win]
    - m2-grep  # [win]
    - m2-sed  # [win]
    - m2-gawk  # [win]
    - m2-diffutils  # [win]
    - m2-perl  # [win]
  commands:
    - codes_info
    - ls $(codes_info -s)  # [not win]
    - ls $(codes_info -d)  # [not win]

about:
  home: https://confluence.ecmwf.int/display/ECC/ecCodes+Home
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: ECMWF ecCodes Copyright 2005- ECMWF.

extra:
  recipe-maintainers:
    - joobog
    - shahramn
    - kmuehlbauer
    - kynan
    - ocefpaf
    - pelson
    - StephanSiemen
    - dtip
    - iainrussell
