{% set version = "2.1.0" %}

package:
  name: eccodes
  version: {{ version }}

source:
  url: https://software.ecmwf.int/wiki/download/attachments/45757960/eccodes-{{ version }}-Source.tar.gz
  fn: eccodes-{{ version }}-Source.tar.gz
  sha256: e7382b06d99e9f6558751c888403181cbbac95ea51275c7ff8d41c15c2ccf554

build:
  number: 1
  detect_binary_files_with_prefix: true
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py>=35]

requirements:
  build:
    - cmake
    - msinttypes  # [win and py<35]
    - boost 1.63.*
    - jasper  # [not win]
    - openjpeg
    - libpng >=1.6.28,<1.7
    - libnetcdf 4.4.*
    - perl 5.22.2.1
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]
  run:
    - jasper  # [not win]
    - openjpeg
    - libpng >=1.6.28,<1.7
    - libnetcdf 4.4.*
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]


test:
  commands:
    - codes_info
    - ls $(codes_info -s)  # [not win]
    - ls $(codes_info -d)  # [not win]
    - conda inspect linkages -p $PREFIX eccodes  # [not win]
    - conda inspect objects -p $PREFIX eccodes  # [osx]

about:
  home: https://software.ecmwf.int/wiki/display/ECC/ecCodes+Home
  license: Apache 2.0
  license_family: Apache
  summary: ECMWF ecCodes Copyright 2005-2017 ECMWF.

extra:
  recipe-maintainers:
    - kmuehlbauer
    - pelson
    - ocefpaf
    - kynan
