{% set version = "0.13.0" %}

package:
  name: eccodes
  version: {{ version }}

source:
  url: https://software.ecmwf.int/wiki/download/attachments/45757960/eccodes-{{ version }}-Source.tar.gz
  fn: eccodes-{{ version }}-Source.tar.gz
  md5: 46a0a520f647cfa2fb5f287f22269603

build:
  number: 2
  skip: true  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - boost 1.61.*
    - jasper
    - libpng >=1.6.21,<1.7
    - libnetcdf 4.4.*
    - perl
  run:
    - boost 1.61.*
    - jasper
    - libpng >=1.6.21,<1.7
    - libnetcdf 4.4.*

test:
  commands:
    - codes_info
    - ls $(codes_info -s)
    - ls $(codes_info -d)

about:
  home: https://software.ecmwf.int/wiki/display/ECC/ecCodes+Home
  license: Apache License Version 2.0, January 2004
  summary: ECMWF ecCodes Copyright 2005-2016 ECMWF.

extra:
  recipe-maintainers:
    - kmuehlbauer
    - pelson
    - ocefpaf
