{% set version = "2.22.0" %}

package:
  name: eccodes
  version: {{ version }}

source:
  url: https://confluence.ecmwf.int/download/attachments/45757960/eccodes-{{ version }}-Source.tar.gz
  sha256: c644a939f9f1fb46c01d7c69b2b3cf988158d03f1c8e11b0494d2b2236ed3448
  patches:
    - fix-tests-path.patch

build:
  number: 0
  skip: true  # [win and vc<14]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cmake
    - jasper  # [not win]
    - openjpeg   # [win]
    - libpng
    - libnetcdf
    - libaec  # [not win]
    - hdf5
  run:
    - jasper  # [not win]
    - openjpeg   # [win]
    - libpng
    - libnetcdf
    - libaec  # [not win]
    - hdf5

test:
  requires:
    - perl  # [not win]
    - m2-bash  # [win]
    - m2-findutils  # [win]
    - m2-coreutils  # [win]
    - m2-grep  # [win]
    - m2-sed  # [win]
    - m2-gawk  # [win]
    - m2-diffutils  # [win]
    - m2-perl  # [win]
  commands:
    - codes_info
    - ls $(codes_info -s)  # [not win]
    - ls $(codes_info -d)  # [not win]
    - for /F "tokens=* USEBACKQ" %%F IN (`codes_info -s`) DO (ls %%F)  # [win]
    - for /F "tokens=* USEBACKQ" %%F IN (`codes_info -d`) DO (ls %%F)  # [win]

about:
  home: https://software.ecmwf.int/wiki/display/ECC/ecCodes+Home
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: ECMWF ecCodes Copyright 2005- ECMWF.

extra:
  recipe-maintainers:
    - kmuehlbauer
    - kynan
    - ocefpaf
    - pelson
    - StephanSiemen
    - dtip
    - iainrussell
