{% set version = "2.0.2" %}

package:
  name: eccodes
  version: {{ version }}

source:
  url: https://software.ecmwf.int/wiki/download/attachments/45757960/eccodes-{{ version }}-Source.tar.gz
  fn: eccodes-{{ version }}-Source.tar.gz
  sha256: e0368dd4dbd85edfd6a9fbe442a10fea611a773550f7ea7ce1f56ee0b340f6cb

build:
  number: 1
  skip: true  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - boost 1.63.*
    - jasper
    - libpng >=1.6.23,<1.7
    - libnetcdf 4.4.*
    - perl
  run:
    - jasper
    - libpng >=1.6.23,<1.7
    - libnetcdf 4.4.*

test:
  commands:
    - codes_info
    - ls $(codes_info -s)
    - ls $(codes_info -d)

about:
  home: https://software.ecmwf.int/wiki/display/ECC/ecCodes+Home
  license: Apache 2.0
  license_family: Apache
  summary: ECMWF ecCodes Copyright 2005-2016 ECMWF.

extra:
  recipe-maintainers:
    - kmuehlbauer
    - pelson
    - ocefpaf
    - kynan
