{% set version = "2.10.0" %}

package:
  name: eccodes
  version: {{ version }}

source:
  url: https://software.ecmwf.int/wiki/download/attachments/45757960/eccodes-{{ version }}-Source.tar.gz
  sha256: bea3cb4caafca368538bc457075bbe848215085f3574cfcdf106d32e954d82d8

build:
  number: 1000
  skip: true  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - perl
    - jasper
    - libpng
    - libnetcdf
    - libaec
    - hdf5
  run:
    - jasper
    - libpng
    - libnetcdf
    - libaec
    - hdf5

test:
  commands:
    - codes_info
    - ls $(codes_info -s)
    - ls $(codes_info -d)

about:
  home: https://software.ecmwf.int/wiki/display/ECC/ecCodes+Home
  license: Apache 2.0
  license_family: Apache
  summary: ECMWF ecCodes Copyright 2005-2018 ECMWF.

extra:
  recipe-maintainers:
    - kmuehlbauer
    - kynan
    - ocefpaf
    - pelson
    - StephanSiemen
