{% set version = "2.11.0" %}

package:
  name: eccodes
  version: {{ version }}

source:
  url: https://software.ecmwf.int/wiki/download/attachments/131371724/eccodes-{{ version }}-Source.tar.gz
  sha256: 455c05badd3554d6f67dff713f6991164b43ed835e1b8a9da7b728499f22932d

build:
  number: 1003
  skip: true  # [win and vc<14]
  detect_binary_files_with_prefix: true
  features:
    - vc14  # [win and py>=35]

requirements:
  build:
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cmake
    - m2-bash  # [win]
    - m2-findutils  # [win]
    - m2-coreutils  # [win]
    - m2-grep  # [win]
    - m2-sed  # [win]
    - m2-gawk  # [win]
    - m2-diffutils  # [win]
    - perl  # [not win]
    - m2-perl  # [win]
    - jasper  # [not win]
    - libpng  # [not win]
    - libnetcdf
    - libaec  # [not win]
    - hdf5
  run:
    - jasper  # [not win]
    - libpng  # [not win]
    - libnetcdf
    - libaec  # [not win]
    - hdf5

test:
  commands:
    - codes_info
    - ls $(codes_info -s)  # [not win]
    - ls $(codes_info -d)  # [not win]
    - for /F "tokens=* USEBACKQ" %%F IN (`codes_info -s`) DO (ls %%F)  # [win]
    - for /F "tokens=* USEBACKQ" %%F IN (`codes_info -d`) DO (ls %%F)  # [win]

about:
  home: https://software.ecmwf.int/wiki/display/ECC/ecCodes+Home
  license: Apache 2.0
  license_family: Apache
  summary: ECMWF ecCodes Copyright 2005-2018 ECMWF.

extra:
  recipe-maintainers:
    - kmuehlbauer
    - kynan
    - ocefpaf
    - pelson
    - StephanSiemen
